## Breast Cancer Data(feature가 30개)
    - 차원 축소 (2, 5, 10) - 설명력
    - PCA 전후 분류(Logistic Regression) 비교

* 데이터 정규화

In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
df = pd.DataFrame(cancer.data, columns=cancer.feature_names)
df['target'] = cancer.target
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [30]:
from sklearn.preprocessing import StandardScaler
cancer_std = StandardScaler().fit_transform(cancer.data)
cancer_std[:2]

array([[ 1.09706398e+00, -2.07333501e+00,  1.26993369e+00,
         9.84374905e-01,  1.56846633e+00,  3.28351467e+00,
         2.65287398e+00,  2.53247522e+00,  2.21751501e+00,
         2.25574689e+00,  2.48973393e+00, -5.65265059e-01,
         2.83303087e+00,  2.48757756e+00, -2.14001647e-01,
         1.31686157e+00,  7.24026158e-01,  6.60819941e-01,
         1.14875667e+00,  9.07083081e-01,  1.88668963e+00,
        -1.35929347e+00,  2.30360062e+00,  2.00123749e+00,
         1.30768627e+00,  2.61666502e+00,  2.10952635e+00,
         2.29607613e+00,  2.75062224e+00,  1.93701461e+00],
       [ 1.82982061e+00, -3.53632408e-01,  1.68595471e+00,
         1.90870825e+00, -8.26962447e-01, -4.87071673e-01,
        -2.38458552e-02,  5.48144156e-01,  1.39236330e-03,
        -8.68652457e-01,  4.99254601e-01, -8.76243603e-01,
         2.63326966e-01,  7.42401948e-01, -6.05350847e-01,
        -6.92926270e-01, -4.40780058e-01,  2.60162067e-01,
        -8.05450380e-01, -9.94437403e-02,  1.80592744e+

- 차원 축소 (2, 5, 10) - 설명력

In [31]:
# 2차원으로 축소
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
cancer_pca = pca.fit_transform(cancer_std)
cancer_pca[:3]

array([[ 9.19283683,  1.94858307],
       [ 2.3878018 , -3.76817174],
       [ 5.73389628, -1.0751738 ]])

In [32]:
# 2차원 축소 설명력
pca.explained_variance_ratio_

array([0.44272026, 0.18971182])

In [33]:
# 5차원으로 축소
pca2 = PCA(n_components=5)
cancer_pca2 = pca2.fit_transform(cancer_std)
cancer_pca2[:3]

array([[ 9.19283683,  1.94858307, -1.12316616,  3.63373067, -1.19510952],
       [ 2.3878018 , -3.76817175, -0.52929279,  1.11826417,  0.62177379],
       [ 5.73389628, -1.0751738 , -0.5517475 ,  0.91208229, -0.17708552]])

In [34]:
# 5차원 축소 설명력
pca2.explained_variance_ratio_

array([0.44272026, 0.18971182, 0.09393163, 0.06602135, 0.05495768])

In [35]:
# 10차원으로 축소
pca3 = PCA(n_components=10)
cancer_pca3 = pca3.fit_transform(cancer_std)
cancer_pca3[:3]

array([[ 9.19283683,  1.94858307, -1.12316617,  3.6337308 , -1.19511017,
         1.41142467,  2.15936916, -0.39842149, -0.15712786, -0.87745816],
       [ 2.3878018 , -3.76817174, -0.52929268,  1.11826394,  0.62177502,
         0.02865618,  0.01335843,  0.24100096, -0.71189623,  1.10704089],
       [ 5.73389628, -1.0751738 , -0.5517476 ,  0.91208249, -0.17708598,
         0.5414526 , -0.66816872,  0.09734663,  0.02404613,  0.45417252]])

In [36]:
# 10차원 축소 설명력
pca3.explained_variance_ratio_

array([0.44272026, 0.18971182, 0.09393163, 0.06602135, 0.05495768,
       0.04024522, 0.02250734, 0.01588724, 0.01389649, 0.01168978])

In [37]:
# # 원본 1차원
# pca0 = PCA(n_components=None)
# cancer_pca0 = pca0.fit_transform(cancer_std)
# pca0.explained_variance_ratio_

In [38]:
# 정규화한 값을 Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(
    cancer_std, cancer.target, stratify=cancer.target, random_state=2021
)
lr = LogisticRegression(random_state=2021)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.993006993006993

- PCA 전후 분류(Logistic Regression) 비교

In [40]:
def pca_accuracy(X, y):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, stratify=y, random_state=2021
    )
    lr = LogisticRegression(random_state=2021)
    lr.fit(X_train, y_train)
    score = lr.score(X_test, y_test)
    return score

In [41]:
for d in [2, 5, 10]:
    pca = PCA(n_components=d)
    cancer_pca = pca.fit_transform(cancer_std)
    explained = sum(pca.explained_variance_ratio_)
    acc = pca_accuracy(cancer_pca, cancer.target)
    print('PCA {}차원의 설명력: {}, 정확도: {}'.format(d, round(explained, 4), round(acc, 4)))

PCA 2차원의 설명력: 0.6324, 정확도: 0.9441
PCA 5차원의 설명력: 0.8473, 정확도: 0.993
PCA 10차원의 설명력: 0.9516, 정확도: 0.986


In [42]:
# for d in [None, 2, 5, 10]:
#     pca = PCA(n_components=d)
#     cancer_pca = pca.fit_transform(cancer_std)
#     explained = sum(pca.explained_variance_ratio_)
#     acc = pca_accuracy(cancer_pca, cancer.target)
#     print('PCA {}차원의 설명력: {}, 정확도: {}'.format(d, round(explained, 4), round(acc, 4)))